//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiBongDa.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pmEntities : DbContext
    {
        public pmEntities()
            : base("name=pmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<BanThang> BanThang { get; set; }
        public virtual DbSet<CauThu> CauThu { get; set; }
        public virtual DbSet<DoiBong> DoiBong { get; set; }
        public virtual DbSet<TranDau> TranDau { get; set; }
        public virtual DbSet<VongDau> VongDau { get; set; }
    }
}
