//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiBongDa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranDau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TranDau()
        {
            this.BanThang = new HashSet<BanThang>();
        }
    
        public string MaTD { get; set; }
        public string SanTD { get; set; }
        public System.DateTime NgayTD { get; set; }
        public string TySo { get; set; }
        public string DoiKhach { get; set; }
        public string DoiChuNha { get; set; }
        public string Videos { get; set; }
        public string MaVD { get; set; }
        public string MaDoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanThang> BanThang { get; set; }
        public virtual DoiBong DoiBong { get; set; }
        public virtual VongDau VongDau { get; set; }
    }
}
