//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Account
    {

        [DisplayName("ID User")]
        [Required(ErrorMessage ="Not empty")]
        public int ID { get; set; }


        [DisplayName("Name User")]
        [Required(ErrorMessage = "Not empty")]
        public string userName { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Not empty")]
        public string userPassword { get; set; }

        [DisplayName("Role user")]
        [Required(ErrorMessage = "Not empty")]
        public string userRole { get; set; }


        [NotMapped]
        [DisplayName("repeat Password")]
        [Required(ErrorMessage = "Not empty")]
        public string repass { get; set; }
    }
}
