//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanThang
    {
        public string MaBT { get; set; }
        public string MaCT { get; set; }
        public string TenCT { get; set; }
        public string MaDoi { get; set; }
        public string MaTD { get; set; }
    
        public virtual CauThu CauThu { get; set; }
        public virtual DoiBong DoiBong { get; set; }
    }
}
