//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauThu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CauThu()
        {
            this.BanThang = new HashSet<BanThang>();
        }
    
        public string MaCT { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string TenCT { get; set; }
        public string ViTri { get; set; }
        public int SoAo { get; set; }
        public string CanNang { get; set; }
        public string MaDoi { get; set; }
        public string Images { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanThang> BanThang { get; set; }
        public virtual DoiBong DoiBong { get; set; }
    }
}
