//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTranDau
    {
        public string MaCTTD { get; set; }
        public string MaTD { get; set; }
        public System.DateTime NgayGio { get; set; }
        public string MaDoiThu1 { get; set; }
        public string MaDoiThu2 { get; set; }
        public string DiaDiem { get; set; }
        public string SanVanDong { get; set; }
        public string KetQua { get; set; }
        public Nullable<int> SoLuongKhanGia { get; set; }
        public string TrongTai { get; set; }
        public Nullable<int> ThoiLuong { get; set; }
    
        public virtual DoiBong DoiBong { get; set; }
        public virtual DoiBong DoiBong1 { get; set; }
        public virtual TranDau TranDau { get; set; }
    }
}
