//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLGIAIBONGDAEntities : DbContext
    {
        public QLGIAIBONGDAEntities()
            : base("name=QLGIAIBONGDAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<BanThang> BanThangs { get; set; }
        public virtual DbSet<CauThu> CauThus { get; set; }
        public virtual DbSet<ChiTietTranDau> ChiTietTranDaus { get; set; }
        public virtual DbSet<DoiBong> DoiBongs { get; set; }
        public virtual DbSet<NhaTaiTro> NhaTaiTroes { get; set; }
        public virtual DbSet<TranDau> TranDaus { get; set; }
        public virtual DbSet<VongDau> VongDaus { get; set; }
    }
}
