//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaTaiTro
    {
        public string MaNTT { get; set; }
        public string TenNTT { get; set; }
        public string LoaiTaiTro { get; set; }
        public string ThongTinLienHe { get; set; }
        public string GhiChu { get; set; }
    }
}
